### ISSUE TITLE
Loading environment variables from different context doesn't work

### ISSUE THREAD

**Issue by marvin-w** [gosuri/vagrant-env#1]
Hello,

firstly, thanks for your plugin.

It works fine if the .env file and the Vagrantfile are in the same directory, but unfortunetly if I hit vagrant up from a different directory than the one the .env is located it fails instantly.

I wantto do sth like

`d.pull_images ENV['REGISTRY_ENDPOINT'] + "/someappPath:" + ENV['RELEASE_VERSION']`

Exception:

`d:/...../Vagrantfile:94:in`block (2 levels) in <top (required)>': undefined method `+' for nil:NilClass (NoMethodError)
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/kernel_v2/config/vm_provisioner.rb:72:in`call'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/kernel_v2/config/vm_provisioner.rb:72:in `add_config'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/kernel_v2/config/vm.rb:311:in`provision'
        from ....Vagrantfile:70:in `block in <top (required)>'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/v2/loader.rb:37:in`call'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/v2/loader.rb:37:in `load'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:103:in`block (2 levels) in load'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:97:in `each'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:97:in`block in load'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:94:in `each'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:94:in`load'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:28:in `initialize'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:691:in`new'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:691:in `vagrantfile'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:441:in`host'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:207:in `block in action_runner'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:33:in`call'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:33:in `run'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:428:in`hook'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:673:in `unload'
        from c:/HashiCorp/Vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:177:in`ensure in <main>'
        from c:/HashiCorp/Vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:177:in `<main>'`

**Comment by gosuri** [comment]
I haven't really considered this particular use case, but will consider this as a bug and will get to it on my first opportunity.

Please feel free to send a pull request if you have a fix, thanks for reporting!

**Comment by gosuri** [comment]
Fixed with #3
