### ISSUE TITLE
The latest commit messed up the tool on Ubuntu 12.04

### ISSUE THREAD

**Issue by swarupdonepudi** [gosuri/vagrant-env#4]
I have been using this tool for a while now and it works awesome. This tool stopped working since the last two hours and found that there was a new commit exactly around that time. This needs to be fixed.

**Comment by gosuri** [comment]
Can you use v0.0.2 while I investigate this issue?

**Comment by gosuri** [comment]
The  latest version (0.0.3) works fine for me. I need to know more information to debug:

1) Plugin version
2) Vagrant version
3) Error message

The commit wouldn't affect you unless you ran `vagrant plugin update`.  If you are running version 0.0.3, try using installing the older version using `vagrant plugin install vagrant-env --plugin-version 0.0.2`

**Comment by swarupdonepudi** [comment]
Vagrant version is : 1.7.4
Plugin versions : 0.0.3 ( Did not work) , 0.0.2(Working)
OS Version : Ubuntu 12.04

Here is the 10 secs screencast

https://asciinema.org/a/954xvzflsmm2yt8wtybx3e8ou

Please let me know if you need anymore information.

**Comment by gosuri** [comment]
You're missing `config.env.enable` in the Vagrantfile. See https://github.com/gosuri/vagrant-env#usage

**Comment by swarupdonepudi** [comment]
gotcha. I missed i. My bad. Is it kind of enforced in version 0.0.3? because it works fine with that line in the Vagrantfile for version 0.0.2. Just curious. Thanks for the find though.

**Comment by gosuri** [comment]
I was a always requirement. Enforced more strictly in the new version.

**Comment by swarupdonepudi** [comment]
Thanks for your help.

**Comment by gosuri** [comment]
:+1:
